services:
  postgres:
    hostname: sleepless_db
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sleepless
    #          POSTGRES_PORT: 5433
    ports:
      - "5432:5432"
    volumes:
      - ./other/postgres-data:/var/lib/postgresql/data
    profiles:
      - env

  mongo:
    #Одна из последних версий которая работает на старом АРМ для RPI4
    image: mongo:4.4.18
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=sleepless
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=root
    volumes:
      - ./other/mongo-data/db:/data/db/
      - ./other/mongo-data/log:/var/log/mongodb/
      - ./other/mongo-data/entrypoint:/docker-entrypoint-initdb.d/
    command: [ "--bind_ip", "0.0.0.0" ]
    profiles:
      - env

  es:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    hostname: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./other/es:/usr/share/elasticsearch/data
    profiles:
      - env

  kibana:
    image: kibana:8.7.1
    volumes:
      - ./other/kibana/config:/usr/share/kibana/config
    environment:
      ELASTICSEARCH_HOSTS: '["http://es:9200"]'
      SERVER_HOST: 0.0.0.0
    ports:
      - "5601:5601"
    profiles:
      - env

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    profiles:
      - env

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
    profiles:
      - env

  sleepless1:
    build:
      dockerfile: DockerfileSleepless
      context: Sleepless/.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sleepless
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin
      SPRING_DATA_MONGODB_DATABASE: sleepless
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true

      ES_ADDRESS: http://es:9200

      TARGET_CHANNEL: melharucos
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - es
      - postgres
    profiles:
      - app
      - app1

#  sleepless2:
#    build:
#      dockerfile: DockerfileSleepless
#      context: Sleepless/.
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sleepless
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root123
#
#      SPRING_DATA_MONGODB_HOST: mongo
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_USERNAME: admin
#      SPRING_DATA_MONGODB_PASSWORD: admin
#      SPRING_DATA_MONGODB_DATABASE: sleepless
#      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
#      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true
#
#      ES_ADDRESS: http://es:9200
#
#      TARGET_CHANNEL: just_ns
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mongo
#      - es
#      - postgres
#    profiles:
#      - app
#      - app2
#
#  sleepless3:
#    build:
#      dockerfile: DockerfileSleepless
#      context: Sleepless/.
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sleepless
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root123
#
#      SPRING_DATA_MONGODB_HOST: mongo
#      SPRING_DATA_MONGODB_PORT: 27017
#      SPRING_DATA_MONGODB_USERNAME: admin
#      SPRING_DATA_MONGODB_PASSWORD: admin
#      SPRING_DATA_MONGODB_DATABASE: sleepless
#      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
#      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true
#
#      ES_ADDRESS: http://es:9200
#
#      TARGET_CHANNEL: RoadHouse
#    ports:
#      - "8082:8082"
#    depends_on:
#      - mongo
#      - es
#      - postgres
#    profiles:
#      - app
#      - app3