version: "3.9"
services:
  postgres:
    hostname: sleepless_db
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: sleepless
    #          POSTGRES_PORT: 5433
    ports:
      - "5432:5432"
    volumes:
      - ./other/postgres-data:/var/lib/postgresql/data

  mongo:
    #Одна из последних версий которая работает на старом АРМ для RPI4
    image: mongo:4.4.18
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=sleepless
      - MONGO_DB_USERNAME=root
      - MONGO_DB_PASSWORD=root
    volumes:
      - ./other/mongo-data/db:/data/db/
      - ./other/mongo-data/log:/var/log/mongodb/
      - ./other/mongo-data/entrypoint:/docker-entrypoint-initdb.d/
    command: [ "--bind_ip", "0.0.0.0" ]

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    hostname: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./other/es:/usr/share/elasticsearch/data

  sleepless_listener:
    build:
      dockerfile: DockerfileSleepless
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sleepless
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123

      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: admin
      SPRING_DATA_MONGODB_DATABASE: sleepless
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_AUTO_INDEX_CREATION: true

      ES_ADDRESS: es
    ports:
      - "8080:8080"
    depends_on:
      - mongo
